export const SWAGGER_TAGS = {
  ACCOUNTS: 'Accounts',
  NFT: 'NFT',
  JETTONS: 'Jettons',
  DNS: 'DNS',
  WALLET: 'Wallet',
  RATES: 'Rates',
  STAKING: 'Staking',
  EXTRA_CURRENCY: 'ExtraCurrency',
  TRACES: 'Traces',
  EVENTS: 'Events',
  STORAGE: 'Storage',
  CONNECT: 'Connect',
  GASLESS: 'Gasless',
  MULTISIG: 'Multisig',
  BLOCKCHAIN: 'Blockchain',
  LITE_SERVER: 'Lite Server',
  EMULATION: 'Emulation',
  INSCRIPTIONS: 'Inscriptions',
  UTILITIES: 'Utilities',
} as const;
